# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Yally' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Yally
pod ‘RxSwift’, ‘~> 5’
pod ‘RxCocoa’, ‘~> 5’
pod ‘Alamofire’, ‘~> 5.2’
pod ‘SwiftLint’
pod 'TextFieldEffects'
pod 'XLPagerTabStrip', '~> 9.0'
pod 'CircleMenu'
pod 'NSObject+Rx'
pod 'RxAlamofire'
pod "SGCodeTextField"
pod 'Moya', '~> 14.0'

end
